<?php
/**
 * @category    Inchoo
 * @package     Inchoo_FoxMetrics
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Inchoo
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<!-- AJZELE -->
<?php $_product = $this->getProductToShoppingCart() ?>
<?php if ($_product && $_product->getId()): ?>
<script type="text/javascript">
    _fxm.events.push(['_fxm.ecommerce.cartitem', '<?php echo $_product->getId() ?>', '<?php echo $_product->getName() ?>','<?php echo $_product->getCategoryName() ?>', '<?php echo $_product->getQty() ?>', '<?php echo $_product->getPrice() ?>']);
</script>
<?php endif; ?>