<?php
/**
 * @category    Inchoo
 * @package     Inchoo_FoxMetrics
 * @author      Branko Ajzele <ajzele@gmail.com>
 * @copyright   Copyright (c) Inchoo
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if (($orderInfo = $this->getOrderInfo())): ?>
<script type="text/javascript">
    <?php foreach ($orderInfo->getItems() as $product): ?>
        _fxm.events.push(['_fxm.ecommerce.purchaseitem', '<?php echo $product->getId() ?>', '<?php echo $product->getName() ?>',
            '<?php echo $product->getCategoryName() ?>', '<?php echo $product->getQty() ?>', '<?php echo $product->getPrice() ?>', '<?php echo $product->getOrderId() ?>']);
    <?php endforeach; ?>

    _fxm.events.push(['_fxm.ecommerce.order', '<?php echo $orderInfo->getId() ?>', '<?php echo $orderInfo->getSubtotal() ?>', '<?php echo $orderInfo->getShippingTotal() ?>',
        '<?php echo $orderInfo->getTaxTotal() ?>', '<?php echo $orderInfo->getBillingCity() ?>', '<?php echo $orderInfo->getBillingState() ?>', '<?php echo $orderInfo->getBillingZip() ?>', '<?php echo $orderInfo->getQty() ?>']);
</script>
<?php endif; ?>